spring:
  application:
    name: app
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development

logging:
  level:
    root: WARN
    org:
      springframework:
        security: trace

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem