spring:
  application:
    name: Task manager
datasource:
  driver-class-name: org.h2.Driver   # общий драйвер (будет переопределен для prod)
jpa:
  ddl-auto: update
  show-sql: true
  properties:
  hibernate:
    format_sql: true